config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/devel/emails"
  end

  ActiveAdmin.routes(self)
  devise_for :people, controllers: { registrations: "people/registrations" }

  resources :inbox, only: [:index, :create, :show]
  resources :messages, only: [:new, :create]
  resources :follow, only: [:index, :create, :update]

  namespace :payments do
    # Braintree routes - Not using currently
    # get "/new" => "braintree#new", as: :purchase_new
    # post "/merchant" => "braintree#create", as: :merchant
    # post "/purchase" => "braintree#purchase", as: :purchase
    # post "/braintree_webhook" => "braintree#braintree_webhook", as: :sub_merchant_webhook

    # Paypal routes
    get "/checkout_paypal" => "paypal#checkout", as: :checkout_paypal
    post "/webhook" => "paypal#webhook"
    post "/confirm" => "paypal#confirm", as: :confirm_checkout
  end

  resources :listings, except: [:show, :edit, :update, :destroy] do
    collection do
      get "details/:slug" => "listings#show", as: :detail
      get ":slug/edit" => "listings#edit", as: :edit
      put ":slug/update" => "listings#update", as: :update
      delete ":slug/destroy" => "listings#destroy", as: :destroy
      post "uploads/" => "listings#uploads", :constraints => { :format => 'json' }
      delete "delete_uploads/:upload_id" => "listings#destroy_uploads", :constraints => { :format => 'json' }
      get "collect_size/:product_type_id" => "listings#collect_size"
    end
  end
  resources :settings, only: [:index] do
    collection do
      put "/" => "settings#update"
      post "/preferences" => "settings#preferences"
      put "/remove_avatar" => "settings#remove_avatar"
      SettingsHelper.settings_list.each do |list|
        get list[0]
      end
    end
  end

  get "profiles/:username" => "profiles#show", as: :profiles

  get '/inventory' => "home#inventory"
  get '/designers' => "home#designers"
  get '/verify_unread_message' => "home#verify_unread_message"
  get 'about_us' => "home#about_us", as: :about_us
  get 'contact_us' => "home#contact_us"

  root to: "home#inventory"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile

  def show
    if @person.has_address?
      set_geocode_location!(@person.address)
    end

    @listings = @person.listings.paginate(:page => params[:page], :per_page => Listing::PER_PAGE)

    respond_to do |format|
      format.html do |html|
        html.phone
      end
    end
  end

  private

  def set_profile
    @person = Person.find_by_username(params[:username])

    if !@person
      redirect_to root_path, flash: { alert: "Page not found" }
    end
  end
end

app/views/profiles/_side_section.html.haml
- content_for :javascript do
  $location = new Location();
  $location.initializeLocation();
  $location.setMap();

  Inbox.initializeMessageBox();
  Follow.initializeFollowings();

- if current_person and !@person.is_current_person?(current_person)
  .side-content
    = link_to "Message", "#", id: "message-box-link", data: { url: new_message_path(receiver_id: @person.id) }, class: "btn btn-default btn-block"
    - if current_person.following_a_person(@person.id).present?
      = link_to "Unfollow", follow_path(current_person.following_a_person(@person.id).id), data: { method_type: :put, follow: true }, class: "btn btn-default btn-block", id: "follow-person"
    - else
      = link_to "Follow", follow_index_path(follower_id: @person.id), data: { method_type: :post, follow: false }, class: "btn btn-default btn-block", id: "follow-person"
    -# = link_to "Feedback", "#", class: "btn btn-default btn-block"
#google-maps

app/views/profiles/show.html+phone.haml
.profile
  .cover-img{style: "background: url('#{@person.cover_image.url(:medium)}');"}
  .top-content
    = person_mobile_view_avatar(@person, inner_class: "alphabetical-avatar")
    - if @person.location
      %ul.list-inline.contact.text-center
        %li
          %span.location
            %i.fa.fa-map-marker
          = @person.location

    %ul.list-inline.text-center
      %li
        %span.value= @person.listings.count
        %br/
        %label Items
      %li
        %span.value= 0
        %br/
        %label Sales
      %li
        %span.value= @person.followers.count
        %br/
        %label
          - if current_person and @person.is_current_person?(current_person)
            = link_to "Followers", follow_index_path
          - else
            Followers

      %li
        %span.value= @person.followings.count
        %br/
        %label
          - if current_person and @person.is_current_person?(current_person)
            = link_to "Following", follow_index_path
          - else
            Following

  .separator-content
  - if @listings.present?
    .listings
      .row
        = render partial: "listings/listing", collection: @listings
    .items-pagination
      = will_paginate @listings, renderer: BootstrapPagination::Rails
  - else
    .alert.alert-success
      There are no listings

  = render  partial: "side_section"
%br/
.message-box

app/views/profiles/show.html.haml
.profile
  .container
    .cover-img{style: "background: url('#{@person.cover_image.url(:medium)}');"}
    .top-content
      .row
        .col-md-1.col-sm-1.col-xs-12
        .col-md-2.col-sm-2.col-xs-12
          = person_avatar @person, inner_class: "alphabetical-avatar-user-profile", outer_class: "image-profile thumbnail"
        .col-md-9.col-sm-9.col-xs-12
          .profile-text
            %h1= @person.full_name
            %ul.list-inline.contact
              %li= @person.tagged_username
              %li
                %span.location
                  %i.fa.fa-map-marker
                = @person.location
          .profile-desc
            .row
              .col-md-6.col-lg-6
                %p.desc
                  = @person.about_you
              .col-md-6.col-lg-6
                %ul.list-inline.additional-details
                  %li
                    %span.value
                      = @person.listings.count
                    %br/
                    %span.label
                      Items
                  %li
                    %span.value
                      = @person.try(:sales) || 0
                    %br/
                    %span.label
                      Sales
                  %li.followers
                    %span.value
                      = @person.followers.count
                    %br/
                    %span.label
                      - if current_person and @person.is_current_person?(current_person)
                        = link_to "Followers", follow_index_path
                      - else
                        Followers
                  %li.followings
                    %span.value
                      = @person.followings.count
                    %br/
                    %span.label
                      - if current_person and @person.is_current_person?(current_person)
                        = link_to "Following", follow_index_path
                      - else
                        Following
                  -# %li.feedback
                    %span.value
                      5/5
                    %br/
                    %span.label
                      + Feedback
    .bottom-content
      .row
        .col-md-6.col-sm-6.col-xs-6
          %ul.list-inline.listing-tabs
            %li.active{:role => "presentation"}
              %a{"aria-controls" => "items", "data-toggle" => "tab", :href => "#items", :role => "tab"} Items:
            -# %li{:role => "presentation"}
              %a{"aria-controls" => "instgram", "data-toggle" => "tab", :href => "#instgram", :role => "tab"} Instagram:
        .col-md-6.col-sm-6.col-xs-6
          - if @person.social_links.any?
            %ul.list-inline.list-right.socal-icons-list
              %li= link_to "", @person.facebook_profile, class: "social-icons-fb", target: "_blank" if @person.facebook_profile.present?
              %li= link_to "", @person.instagram_profile, class: "social-icons-instagram", target: "_blank" if @person.instagram_profile.present?
              -# %li
                = link_to "", "#", class: "social-icons-snapchat"
              %li= link_to "", @person.instagram_profile, class: "social-icons-twitter", target: "_blank" if @person.instagram_profile.present?
              -# %li
                = link_to "", "#", class: "social-icons-pinterest"
      .row
        .col-md-9.col-sm-9.col-xs-9
          .tab-content
            #items.tab-pane.fade.in.active{:role => "tabpanel"}
              - if @listings.present?
                .listings
                  .row
                    = render partial: "listings/listing", collection: @listings
                .items-pagination
                  = will_paginate @listings, renderer: BootstrapPagination::Rails
              - else
                .alert.alert-success
                  There are no listings
            -# #instgram.tab-pane{:role => "tabpanel"}
        .col-md-3.col-sm-3.col-xs-3
          = render  partial: "side_section"
  %br/
  .message-box