config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/devel/emails"
  end

  ActiveAdmin.routes(self)
  devise_for :people, controllers: { registrations: "people/registrations" }

  resources :inbox, only: [:index, :create, :show]
  resources :messages, only: [:new, :create]
  resources :follow, only: [:index, :create, :update]

  namespace :payments do
    # Braintree routes - Not using currently
    # get "/new" => "braintree#new", as: :purchase_new
    # post "/merchant" => "braintree#create", as: :merchant
    # post "/purchase" => "braintree#purchase", as: :purchase
    # post "/braintree_webhook" => "braintree#braintree_webhook", as: :sub_merchant_webhook

    # Paypal routes
    get "/checkout_paypal" => "paypal#checkout", as: :checkout_paypal
    post "/webhook" => "paypal#webhook"
    post "/confirm" => "paypal#confirm", as: :confirm_checkout
  end

  resources :listings, except: [:show, :edit, :update, :destroy] do
    collection do
      get "details/:slug" => "listings#show", as: :detail
      get ":slug/edit" => "listings#edit", as: :edit
      put ":slug/update" => "listings#update", as: :update
      delete ":slug/destroy" => "listings#destroy", as: :destroy
      post "uploads/" => "listings#uploads", :constraints => { :format => 'json' }
      delete "delete_uploads/:upload_id" => "listings#destroy_uploads", :constraints => { :format => 'json' }
      get "collect_size/:product_type_id" => "listings#collect_size"
    end
  end
  resources :settings, only: [:index] do
    collection do
      put "/" => "settings#update"
      post "/preferences" => "settings#preferences"
      put "/remove_avatar" => "settings#remove_avatar"
      SettingsHelper.settings_list.each do |list|
        get list[0]
      end
    end
  end

  get "profiles/:username" => "profiles#show", as: :profiles

  get '/inventory' => "home#inventory"
  get '/designers' => "home#designers"
  get '/verify_unread_message' => "home#verify_unread_message"
  get 'about_us' => "home#about_us", as: :about_us
  get 'contact_us' => "home#contact_us"

  root to: "home#inventory"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
# == Schema Information
#
# Table name: listings
#
#  id                         :integer          not null, primary key
#  name                       :string
#  description                :string
#  category_id                :integer
#  person_id                  :integer
#  price                      :float
#  condition                  :string
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#  slug                       :string
#  company_id                 :integer
#  size_id                    :integer
#  product_type_id            :integer
#  display_image_file_name    :string
#  display_image_content_type :string
#  display_image_file_size    :integer
#  display_image_updated_at   :datetime
#

class Listing < ApplicationRecord
  belongs_to :category
  belongs_to :person
  belongs_to :size
  belongs_to :product_type
  belongs_to :company, class_name: "Designer", foreign_key: :company_id

  has_many :uploads, dependent: :destroy
  has_many :chat_rooms, dependent: :destroy

  has_one :address, as: :owner, dependent: :destroy
  accepts_nested_attributes_for :address

  has_attached_file :display_image, styles: { medium: "400x500#", large: "1200x1200>", banner: "950x505>" }, :default_url => "/assets/profile-icon.png"
  validates_attachment_content_type :display_image, content_type: /\Aimage\/.*\Z/

  include Utilities
  include Common

  validates_presence_of :description, :size
  validates_uniqueness_of :slug

  %w(tops outerwear bottoms shoes accessories).each do |product|
    scope product.to_sym, -> { joins(:size => :product_type).where("lower(product_types.name) = ?", product) }
  end

  CONDITIONS = [
    "1/10", "2/10", "3/10", "4/10", "5/10", "6/10", "7/10", "8/10", "9/10", "Deadstock"
  ]

  PER_PAGE = 30

  def upload_photos(files = [])
    if self.display_image.blank?
      self.display_image = files.first
      save!
    end
    files.each{|file| uploads.create(image: file) }
  end

  def has_address?
    address.present?
  end

  def valid_attribute?(attribute_name)
    self.valid?
    self.errors[attribute_name].blank?
  end

  def self.fetch_by_filters(filters)
    listings = all.includes(:size, :company).order("listings.created_at desc")
    conditions = []

    if filters[:category_ids]
      conditions << "category_id in (:categories)"
    end

    if (filters.keys & ["lower_price", "upper_price"]).length == 2
      conditions << "price >= #{filters[:lower_price]} AND price <= #{filters[:upper_price]}"
    end

    if filters[:product_type].present?
      listings = listings.send(filters[:product_type])
    end

    if filters[:company_ids]
      conditions << "company_id in (:companies)"
    end


    if filters[:size_names].present?
      listings = listings.joins(:size) unless filters[:product_type].present?
      conditions << "sizes.name in (:size_names)"
    end

    if filters[:location].present?
      listings = listings.joins(:address)
      conditions << "addresses.latitude in (:latitude) and addresses.longitude in (:longitude)"
    end

    if filters[:conditions]
      conditions << "condition in (:conditions})"
    end

    if filters[:q].present?
      listings = listings.joins(:company)
      conditions << "(listings.name iLike (:query) OR description iLike (:query) OR designers.name iLike (:query))"
    end

    listings.where(conditions.join(" AND "), {
        size_names: filters[:size_names].try(:uniq), companies: filters[:company_ids],
        categories: filters[:category_ids], condition: filters[:conditions],
        latitude: filters[:latitude], longitude: filters[:longitude],
        query: "%#{filters[:q]}%"
      }
    )
  end

  def belongs_to_person?(person)
    person_id == person.id
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_person!, except: [:show]
  before_action :set_current_person_listing, only: [:edit, :update, :destroy]
  # before_action :fetch_category!, only: [:new, :edit]
  before_action :set_default_request_format, only: [:create, :update]
  before_action :set_listing_data, only: [:new, :edit]

  include Publisher

  def index
    @categories = Category.all
  end

  def new
    @listing = current_person.listings.build
    set_address!(current_person.address)

    @listing.build_address
  end

  def create
    @listing = current_person.listings.build
    change = PlanListing.new(@listing, params)
    change.add_subscriber(PersistenceResponse.new(self))
    change.attributes = listing_params
    change.perform
  end

  def uploads
    listing = Listing.find(fetch_stored_config(:listing_id))
    listing.upload_photos uploads_params[:upload_photos]
    render json: 200
  end

  def destroy_uploads
    upload = Upload.find(params[:upload_id]).destroy
    listing = upload.listing
    if listing.uploads.blank?
      listing.update_attribute(:display_image, nil)
    else
      listing.update_attribute(:display_image, listing.uploads.first.image)
    end
    render json: 200
  end

  def collect_size
    @product_type = ProductType.find(params[:product_type_id])
    @sizes = @product_type.sizes
    respond_to do |format|
      format.js
    end
  end

  def show
    @listing = Listing.includes(:uploads).find_by_slug(params[:slug])
    redirect_to root_path, flash: { alert: "Page not found" } unless @listing

    @uploads = @listing.uploads
    set_geocode_location!(@listing.address)

    respond_to do |format|
      format.html do |html|
        html.phone
      end
    end
  end

  def edit
    set_address!(@listing.address)
  end

  def update
    change = PlanListing.new(@listing, params)
    change.add_subscriber(PersistenceResponse.new(self))
    change.attributes = listing_params
    change.perform
  end

  def destroy
    @listing.destroy
    redirect_to root_path, notice: "Your listing has been successfully removed."
  end

  class PersistenceResponse < SimpleDelegator
    def listing_updated(listing)
      unless params[:attribute_name]
        flash[:notice] = "Your Product has been Saved Successfully"
      end
      render json: { status: 200, redirect_to: root_path }
    end

    def listing_failed(status = false)
      render json: status
    end
  end

  private

    def set_default_request_format
      request.format = :json unless params[:format]
    end

    # Not being used anymore
    def fetch_category!
      @category = if params[:category_slug].present?
                    Category.find_by_slug(params[:category_slug])
                  elsif @listing
                    @listing.category
                  end
      redirect_to listings_path if !@category
    end

    def listing_params
      params.require(:listing).permit(:name, :description, :price, :company_id, :category_id, :condition, :size_id, :product_type_id,
                                      :address_attributes => [:id, :location, :place_id, :latitude, :longitude]
                                     )
    end

    def uploads_params
      params.permit(
        :upload_photos => []
      )
    end

    def set_listing_data
      @products = ProductType.all
      @designers = Designer.all
    end

    def set_current_person_listing
      add_subscriber(self)
      @listing = Listing.includes(:uploads).find_by_slug(params[:slug])
      if (!@listing || (current_person and !@listing.belongs_to_person?(current_person))) and !current_person.admin?
        redirect_to root_path, flash: { alert: "Page not found" }
      end
    end

    def set_address!(address)
      @address = address
      if @address.present?
        set_geocode_location!(@address)
      end
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
  def listing_raw_images(listing)
    uploads = listing.uploads
    images = uploads.map(&:image).map{|v| image_tag v.url(:large), class: "uploaded-img" }
    images_config = []
    uploads.map do |v|
      images_config << {
        'type': "image", 'caption': v.image_file_name, 'size': v.image_file_size, 'upload_id': v.id
      }
    end

    [raw(images), raw(JSON.parse(images_config.to_json).map{|v| v.to_json.gsub("=>", ":")})]
  end
end

app/views/listings/_form.html.haml
- content_for :javascript do
  $location = new Location();
  $location.initializeLocation();
  $location.setMapForm();

  window.wrapper_upload = $(".listing-uploads").find(".dummy-box");

= form_for @listing, url: action, method: method, html: { id: "listingForm", class: "listing-form", :multipart => true, data: { new_record: @listing.new_record? } }  do |f|
  = hidden_field_tag :listing_id, f.object.id
  .container
    .row
      .col-md-7
        .form-group
          .listing-uploads
            = f.label :uploads, "Images"
            = file_field_tag "upload_photos[]", multiple: true, id: "listing_upload_photos", class: "file-field-input"
            #file-upload-error-container.file-status-container
            #file-upload-success-container.file-status-container
      .col-md-5
        = validation_errors_notifications(@listing)
        -# = f.hidden_field :category_id, value: @category.id
        .form-group
          = f.label :name, "Title"
          %br/
          = f.text_field :name, autofocus: true, class: "form-control input-lg"
        .form-group
          = f.label :description, "Detailed Description"
          %br/
          = f.text_area :description, class: "form-control input-lg"
        .form-group
          = f.label :product_type
          %br/
          = f.select :product_type_id, options_for_select(@products.map{ |v| [v.name, v.id] }, f.object.product_type_id), { include_blank: "--Select Product Type--" }, class: "form-control input-lg product-type-listing-input"
        .product-size
          .form-group
            -# Size field will be output
            - unless f.object.new_record?
              = yield f
        .form-group
          = f.label :price
          %br/
          = f.number_field :price, class: "form-control input-lg"
        .form-group
          = f.label :condition
          %br/
          = f.select :condition,  Listing::CONDITIONS.map{ |v| v }, { include_blank: "Select Condition" }, class: "form-control input-lg"

        .form-group
          = f.label :company, "Company/Designers"
          %br/
          = f.select :company_id,  @designers.map{ |v| [v.name, v.id] }, { include_blank: "Select Company/Designers" }, class: "form-control input-lg"

        .form-group
          = f.fields_for :address do |n|
            = n.label :location
            = n.text_field :location, value: @address.try(:location), class: "form-control input-lg", id: "location_input"
            = n.hidden_field :latitude, class: "form-control input-lg", id: "latitude_input"
            = n.hidden_field :longitude, class: "form-control input-lg", id: "longitude_input"
            = n.hidden_field :place_id, value: @address.try(:place_id), class: "form-control input-lg", id: "place_id_input"
            #google-maps



        .form-actions
          = f.submit "Submit", class: "btn btn-primary site-btn"

app/views/listings/_listing.html.haml
.col-md-3.col-sm-3.col-xs-6.listing-column
  .listing-thumbnail.thumbnail
    %a{href: detail_listings_path(listing.slug)}
      = image_tag listing.display_image.url(:medium)
    .caption
      %p.created= time_ago_in_words((listing.updated_at || listing.created_at))
      .desc
        %h4
          = listing.company.try(:name)
          %small= listing.size.try(:name)
        %p.content
          = listing.name
      %p.price= number_to_currency listing.price

app/views/listings/_size_field.html.haml
.form-group
  = label_tag :sizes
  %br/
  - if sizes.present?
    = select :listing, :size_id, sizes.map{ |v| [v.name, v.id] }, { include_blank: "Select Size" }, class: "form-control input-lg"
  - else
    = select :listing, :size_id, [], { include_blank: "There are no sizes present for #{@product_type.name}" }, class: "form-control input-lg"

app/views/listings/_upload_viewer.html.haml
- content_for :javascript do
  easyzoom = $(".easyzoom-#{upload.id}").easyZoom();
  easyzoom.show();

.modal.fade{"aria-labelledby" => "uploadViewerModal", :role => "dialog", :tabindex => "-1", id: "uploadViewerModal_#{upload.id}"}
  .modal-dialog{role: "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        .easyzoom.easyzoom--overlay.easyzoom--with-toggle.is-ready{style: "width: 100%;", class: "easyzoom-#{upload.id}"}
          = link_to upload.image.url(:large), class: "text-center" do
            = image_tag upload.image.url(:large), class: "img-responsive", style: "max-width: 100%;margin: 0 auto;"

app/views/listings/collect_size.js.erb
<% if @product_type.present? %>
  $("#listingForm").find(".product-size").html("<%= escape_javascript(render partial: 'size_field', locals: { sizes: @sizes }).html_safe %>");
<% else %>
  alert("Couldn't Fetch Product Type")
<% end %>

app/views/listings/edit.html.haml
- images, configs = listing_raw_images(@listing)
- content_for :javascript do
  Listings.initializeListingsForm();
  Listings.refreshFileInput(#{images}, #{configs});

- title "Edit your Listing"
= heading_section :h2, "Sell Item"
.authform.authform-container-fluid
  -# .list-group.categories
    %a.list-group-item.active{:href => listings_path(slug: @listing.slug)}
      Category:
      = @category.name
= render layout: "form", locals: { action: update_listings_path, method: :put } do |f|
  = render partial: "size_field", locals: { sizes: f.object.product_type.sizes }

app/views/listings/index.html.haml
-# Not being used
- title "Listings - Threadhabits"
= heading_section :h2, "Sell Item"
.listings-index
  .authform.authform-container-fluid
    .form-group
      %h4 Select Category
      .list-group.categories
        - @categories.each do |category|
          - if params[:slug].present?
            %a.list-group-item{:href => edit_listings_path(params[:slug], category_slug: category.slug)}
              = category.name
          - else
            %a.list-group-item{:href => new_listing_path(category_slug: category.slug)}
              = category.name

app/views/listings/new.html.haml
- content_for :javascript do
  Listings.initializeListingsForm();
  Listings.toggleFileUploadValidation();

- title "Create a new Listing"
= heading_section :h2, "Sell Item"
.authform.authform-container-fluid
  -# .list-group.categories
    %a.list-group-item.active{:href => listings_path}
      Category:
      = @category.name
= render partial: "form", locals: { action: listings_path, method: :post }

app/views/listings/show.html+phone.haml
- content_for :javascript do
  Inbox.initializeMessageBox();

.listing-details-phone
  #carousel-example-generic.carousel.slide{"data-ride" => "carousel"}
    / Indicators
    %ol.carousel-indicators
      - @uploads.each_with_index do |upload, i|
        %li{class: i == 0 ? "active" : "", "data-slide-to" => i.to_s, "data-target" => "#carousel-example-generic"}

    / Wrapper for slides
    .carousel-inner{:role => "listbox"}
      - @uploads.each_with_index do |upload, i|
        .item{class: i == 0 ? "active" : ""}
          = image_tag upload.image.url(:large), class: "img-responsive listing"
          .carousel-caption
    / Controls
    %a.left.carousel-control{"data-slide" => "prev", :href => "#carousel-example-generic", :role => "button"}
      %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
      %span.sr-only Previous
    %a.right.carousel-control{"data-slide" => "next", :href => "#carousel-example-generic", :role => "button"}
      %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
      %span.sr-only Next

  .details
    .created-at
      = time_ago_in_words((@listing.updated_at || @listing.created_at))

    %ul.list-unstyled.info-section-1
      %li
        %span.pull-left= @listing.company.try(:name)
        %span.pull-right= @listing.size.try(:name)
      %li.row &nbsp;
      %li= @listing.name
      %li
        %span.pull-left= number_to_currency @listing.price
        - if person_signed_in?
          %span.pull-right
            - if current_person.has_followed?(@listing.person)
              %i.fa.fa-heart
            - else
              %i.fa.fa-heart-o

    .row &nbsp;

    - if person_signed_in?
      - unless @listing.person.is_current_person?(current_person)
        = link_to "Message", "#", id: "message-box-link", data: { url: new_message_path(receiver_id: @listing.person.id, listing_id: @listing.id) }, class: "btn btn-default btn-block-lg btn-block"
      - unless @listing.person.is_current_person?(current_person)
        = link_to payments_checkout_paypal_path(listing_id: @listing.id), "data-turbolinks" => false, class: "btn btn-default btn-block btn-block-lg" do
          %i.fa.fa-paypal
          Purchase with Paypal
    - else
      = link_to "Message", new_person_session_path, class: "btn btn-default btn-block-lg btn-block"
      = link_to new_person_session_path, "data-turbolinks" => false, class: "btn btn-default btn-block btn-block-lg" do
        %i.fa.fa-paypal
        Purchase with Paypal

    .info-section-2
      %label Description:
      %p= simple_format @listing.description

      %label Condition:
      = @listing.condition

      %br

      %label Posted By:
      %br

      .person-details
        = person_mobile_view_avatar(@listing.person, inner_class: "alphabetical-avatar")

        %ul.list-inline.text-center
          %li
            %span.value= @listing.person.listings.count
            %br/
            %label Items
          %li
            %span.value= 0
            %br/
            %label Sales
          %li
            %span.value= @listing.person.followers.count
            %br/
            %label Followers

.message-box

app/views/listings/show.html.haml
- content_for :javascript do
  $location = new Location();
  $location.initializeLocation();
  $location.setMap();

  Inbox.initializeMessageBox();

.listing-details
  .row
    .col-md-6.col-sm-6.col-xs-6.box.box-left
      .col-md-12.col-sm-12.col-xs-12#scrolling-section
        .images
          - @uploads.each do |upload|
            = image_tag upload.image.url(:large), class: "img-responsive listing", data: { toggle: "modal", target: "#uploadViewerModal_#{upload.id}" }
            = render partial: "upload_viewer", locals: { upload: upload }
    .col-md-6.col-sm-6.col-xs-6.box.box-right
      .col-md-10.col-sm-12.col-xs-12
        .detailed
          .heading-top
            %h1
              = @listing.company.try(:name)
              .pull-right
                = number_to_currency @listing.price
          .heading-bottom
            %span.item-name
              = @listing.name
            %span.size.pull-right
              = @listing.size.try(:name)

          .description
            = simple_format @listing.description
          .condition
            %label
              Condition:
            = @listing.condition

          .owner-profile
            .col-md-10.col-sm-12.col-xs-12
              .row.profile-details
                .col-md-5.col-sm-5.col-xs-5
                  = link_to profiles_path(@listing.person.username) do
                    = person_avatar(@listing.person, inner_class: "alphabetical-avatar")
                .col-md-7.col-sm-7.col-xs-7
                  .heading
                    = link_to @listing.person.full_name, profiles_path(@listing.person.username)
                  .username
                    = link_to @listing.person.tagged_username, profiles_path(@listing.person.username)
                  .sellings
                    %ul.list-inline
                      %li
                        = @listing.person.listings.count
                        Items
                      -# %li 19 Sales
                  - if person_signed_in?
                    - unless @listing.person.is_current_person?(current_person)
                      = link_to "Message", "#", id: "message-box-link", data: { url: new_message_path(receiver_id: @listing.person.id, listing_id: @listing.id) }, class: "btn btn-default btn-block-lg btn-block"
                  - else
                    = link_to "Message", new_person_session_path, class: "btn btn-default btn-block-lg btn-block"
              - if person_signed_in?
                - unless @listing.person.is_current_person?(current_person)
                  = link_to payments_checkout_paypal_path(listing_id: @listing.id), "data-turbolinks" => false, class: "btn btn-default btn-block btn-block-lg" do
                    %i.fa.fa-paypal
                    Purchase with Paypal
              - else
                = link_to new_person_session_path, "data-turbolinks" => false, class: "btn btn-default btn-block btn-block-lg" do
                  %i.fa.fa-paypal
                  Purchase with Paypal
              -# = link_to "#", class: "btn btn-default btn-block" do
                %i.fa.fa-cart-plus
                Add to cart

              - if (current_person and @listing.belongs_to_person?(current_person)) || (current_person and current_person.admin?)
                .edit-options
                  .row
                    .col-md-6
                      = link_to edit_listings_path(@listing.slug), class: "btn btn-primary btn-block" do
                        %i.fa.fa-pencil
                        Edit
                    .col-md-6
                      = link_to destroy_listings_path(@listing.slug), method: :delete, class: "btn btn-primary btn-block ", data: { confirm: "Are you sure?" } do
                        %i.fa.fa-trash
                        Delete
              #google-maps

.message-box