config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/devel/emails"
  end

  ActiveAdmin.routes(self)
  devise_for :people, controllers: { registrations: "people/registrations" }

  resources :inbox, only: [:index, :create, :show]
  resources :messages, only: [:new, :create]
  resources :follow, only: [:index, :create, :update]

  namespace :payments do
    # Braintree routes - Not using currently
    # get "/new" => "braintree#new", as: :purchase_new
    # post "/merchant" => "braintree#create", as: :merchant
    # post "/purchase" => "braintree#purchase", as: :purchase
    # post "/braintree_webhook" => "braintree#braintree_webhook", as: :sub_merchant_webhook

    # Paypal routes
    get "/checkout_paypal" => "paypal#checkout", as: :checkout_paypal
    post "/webhook" => "paypal#webhook"
    post "/confirm" => "paypal#confirm", as: :confirm_checkout
  end

  resources :listings, except: [:show, :edit, :update, :destroy] do
    collection do
      get "details/:slug" => "listings#show", as: :detail
      get ":slug/edit" => "listings#edit", as: :edit
      put ":slug/update" => "listings#update", as: :update
      delete ":slug/destroy" => "listings#destroy", as: :destroy
      post "uploads/" => "listings#uploads", :constraints => { :format => 'json' }
      delete "delete_uploads/:upload_id" => "listings#destroy_uploads", :constraints => { :format => 'json' }
      get "collect_size/:product_type_id" => "listings#collect_size"
    end
  end
  resources :settings, only: [:index] do
    collection do
      put "/" => "settings#update"
      post "/preferences" => "settings#preferences"
      put "/remove_avatar" => "settings#remove_avatar"
      SettingsHelper.settings_list.each do |list|
        get list[0]
      end
    end
  end

  get "profiles/:username" => "profiles#show", as: :profiles

  get '/inventory' => "home#inventory"
  get '/designers' => "home#designers"
  get '/verify_unread_message' => "home#verify_unread_message"
  get 'about_us' => "home#about_us", as: :about_us
  get 'contact_us' => "home#contact_us"

  root to: "home#inventory"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/inbox_controller.rb
class InboxController < ApplicationController
  before_action :authenticate_person!
  before_action :set_chat_rooms, only: [:index, :show]
  before_action :set_chat_room, only: [:show]

  def index
    @chat_room = @chat_rooms.first
    if @chat_room.present?
      @messages = @chat_room.messages.order("created_at asc")
      @messages.last.mark_as_read if @messages.last.receiver_id == current_person.id
      @message = @chat_room.messages.build
    end
  end

  def show
    @messages = @chat_room.messages.order("created_at asc")
    @messages.last.mark_as_read if @messages.last.receiver_id == current_person.id
    @message = @chat_room.messages.build
  end

  private

  def set_chat_room
    begin
      @chat_room = current_person.chat_rooms.includes(:messages).find(params[:id])
    rescue ActiveRecord::RecordNotFound
      respond_to do |format|
        format.html { redirect_to inbox_index_path, flash: { alert: "Chatroom could not found" } and return }
        format.json { render json: { status: 200, message: "Chatroom could not found" } and return }
      end
    end
  end

  def set_chat_rooms
    @chat_rooms = current_person.chat_rooms.includes(:messages).order("messages.created_at desc")
  end

  def chatroom_params
    params.require(:chat_room).permit(:title, :listing_id, :messages_attributes => [:id, :receiver_id, :sender_id, :body])
  end
end

app/helpers/inbox_helper.rb
module InboxHelper
end

app/views/inbox/_chat_rooms.html.haml
= link_to inbox_path(chat_room.id), class: "list-group-item chat-room #{params[:id].to_i == chat_room.id || (!params[:id] && @chat_rooms[0].id == chat_room.id) ? 'active' : ''}" do
  .row
    .col-md-3.col-sm-3.col-xs-3
      = person_avatar(chat_room.messages.first.sender, inner_class: "alphabetical-avatar-inbox-list", outer_class: "recipient-img recipient-avatar")
    .col-md-9.col-xs-9.col-sm-9
      .top-section
        %span.recipient-name= chat_room.messages.first.sender.full_name
        %span.message-date.pull-right= chat_room.messages.first.created_at.strftime("%B %d, %Y")
      .bottom-section
        = chat_room.messages.first.body
        - if !chat_room.messages.first.has_read? && chat_room.messages.first.receiver_id == current_person.id
          %span.pull-right
            %i.fa.fa-circle

app/views/inbox/_details.html.haml
= render layout: "inbox" do
  - content_for :javascript do
    Inbox.validateForm();

  .message-detail
    - if @chat_room.listing.present?
      .row
        .col-md-9.col-sm-9.col-xs-9.listing
          .col-md-4.col-sm-4.col-xs-4
            = link_to detail_listings_path @chat_room.listing.slug do
              = image_tag @chat_room.listing.display_image.url(:medium), class: "img-responsive recipient-img"
          .col-md-8.col-sm-8.col-xs-8
            %h2
              = link_to detail_listings_path @chat_room.listing.slug do
                = @chat_room.listing.name
              %small.pull-right
                = number_to_currency @chat_room.listing.price
            .item-info
              %label
                Designer/Company:
              = @chat_room.listing.company.name
              %br
              %label
                Size:
              = @chat_room.listing.size.name
              %br
              %label
                Condition:
              = @chat_room.listing.condition
            -# %button.btn.btn-default Add to Cart
            -# %button.btn.btn-default Buy it now
            %br
            = link_to payments_checkout_paypal_path(listing_id: @chat_room.listing.id), "data-turbolinks" => false, class: "btn btn-default btn-block btn-block-lg" do
              %i.fa.fa-paypal
              Purchase with Paypal

    .messages-list
      %ul.list-group
        - @messages.each do |message|
          %li.list-group-item
            .row
              .col-md-2.col-sm-2.col-xs-2
                = link_to profiles_path message.sender.username do
                  = person_avatar(message.sender, inner_class: "alphabetical-avatar-inbox-detail", outer_class: "recipient-avatar")
              .col-md-10.col-xs-10.col-sm-10
                .top-section
                  %span.recipient-name
                  = link_to profiles_path message.sender.username do
                    = message.sender.full_name
                  %span.message-date.pull-right= message.created_at.strftime("%B %d, %Y")
                .bottom-section
                  = message.body
      .message-form
        .row
          .col-md-2.col-sm-2.col-xs-2
            = person_avatar(current_person, inner_class: "alphabetical-avatar-inbox-detail", outer_class: "recipient-avatar")
          .col-md-10.col-xs-10.col-sm-10
            - receiver_id = @messages.select{ |v| v.sender_id == current_person.id }.first.try(:receiver_id) || @messages.last.sender_id
            = render layout: "messages/form", locals: { object: @message, receiver_id: receiver_id, sender_id: current_person.id, chat_room: @chat_room, form_id: "messageFormInbox" } do
              .form-actions.text-right
                %button.btn.btn-primary{:type => "submit"} Reply

app/views/inbox/_inbox.html.haml
.inbox
  .container
    .row
      .col-md-4.col-sm-4.col-xs-4
        %h3.text-center Messages
    .row
      .col-md-4.col-sm-4.col-xs-4.list-section
        .list-group.chat-room-group
          = render partial: "inbox/chat_rooms", collection: @chat_rooms, as: :chat_room
      .col-md-8.col-sm-8.col-xs-8.message-section
        .panel.panel-default
          .panel-body.message-body
            = yield

app/views/inbox/index.html.haml
- if @chat_room.present?
  = render partial: "details"
- else
  .alert.alert-success
    There are no Messages

app/views/inbox/show.html.haml
= render partial: "details"