config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/devel/emails"
  end

  ActiveAdmin.routes(self)
  devise_for :people, controllers: { registrations: "people/registrations" }

  resources :inbox, only: [:index, :create, :show]
  resources :messages, only: [:new, :create]
  resources :follow, only: [:index, :create, :update]

  namespace :payments do
    # Braintree routes - Not using currently
    # get "/new" => "braintree#new", as: :purchase_new
    # post "/merchant" => "braintree#create", as: :merchant
    # post "/purchase" => "braintree#purchase", as: :purchase
    # post "/braintree_webhook" => "braintree#braintree_webhook", as: :sub_merchant_webhook

    # Paypal routes
    get "/checkout_paypal" => "paypal#checkout", as: :checkout_paypal
    post "/webhook" => "paypal#webhook"
    post "/confirm" => "paypal#confirm", as: :confirm_checkout
  end

  resources :listings, except: [:show, :edit, :update, :destroy] do
    collection do
      get "details/:slug" => "listings#show", as: :detail
      get ":slug/edit" => "listings#edit", as: :edit
      put ":slug/update" => "listings#update", as: :update
      delete ":slug/destroy" => "listings#destroy", as: :destroy
      post "uploads/" => "listings#uploads", :constraints => { :format => 'json' }
      delete "delete_uploads/:upload_id" => "listings#destroy_uploads", :constraints => { :format => 'json' }
      get "collect_size/:product_type_id" => "listings#collect_size"
    end
  end
  resources :settings, only: [:index] do
    collection do
      put "/" => "settings#update"
      post "/preferences" => "settings#preferences"
      put "/remove_avatar" => "settings#remove_avatar"
      SettingsHelper.settings_list.each do |list|
        get list[0]
      end
    end
  end

  get "profiles/:username" => "profiles#show", as: :profiles

  get '/inventory' => "home#inventory"
  get '/designers' => "home#designers"
  get '/verify_unread_message' => "home#verify_unread_message"
  get 'about_us' => "home#about_us", as: :about_us
  get 'contact_us' => "home#contact_us"

  root to: "home#inventory"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :authenticate_person!
  before_action :prepend_configuration, :except => [:update]

  @@current_settings = ""

  def profiles
    if current_person.has_address?
      set_geocode_location!(current_person.address)
    else
      current_person.build_address
    end
  end

  def accounts
  end

  def notifications
    @preferences = current_person.preferences.notifications.first.try(:activated) || []
  end

  def payments
    #code
  end

  def update
    @current_settings = @@current_settings
    if current_person.update_attributes(person_params)
      bypass_sign_in(current_person)
      redirect_to fetch_stored_config(:location), notice: "#{@current_settings.capitalize} settings updated successfully"
    else
      flash[:alert] = "Review errors below"
      render @current_settings.to_sym
    end
  end

  def preferences
    @preference = current_person.preferences.notifications.first
    if @preference.blank?
      @preference = current_person.preferences.notifications.build(preference_type: "Notification")
    end
    @preference.data = params[:notification_preferences] || {}
    @preference.save
    redirect_to notifications_settings_path, notice: "Notifications settings updated successfully"
  end

  def remove_avatar
    current_person.send("#{params[:avatar_type]}=", nil)
    current_person.save!
    redirect_to profiles_settings_path, notice: "Image Removed Successfully"
  end

  private
    def person_params
      permitted_attributes =  case @@current_settings.to_sym
                              when :profiles
                               [:first_name, :last_name, :email,
                               :password, :password_confirmation,
                               :phone_number, :about_you, :avatar, :cover_image, :facebook_profile, :instagram_profile, :twitter_profile,
                               :address_attributes => [:id, :location, :place_id, :latitude, :longitude]]
                              when :accounts
                               [:email, :username, :password, :password_confirmation, :current_password]
                              else
                                [:paypal_id]
                              end
      params.require(:person).permit(permitted_attributes).merge!(setting_tab: @@current_settings)
    end

    def prepend_configuration
      @@current_settings = params[:action]
      store_config(location: request.url)
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
  module_function

  def settings_list
    {
      "profiles" => {
        name: "Profile Info",
        path: defined?(profiles_settings_path) ? profiles_settings_path : nil
      },
      "accounts" => {
        name: "Account",
        path: defined?(accounts_settings_path) ? accounts_settings_path : nil
      },
      "notifications" => {
        name: "Notifications",
        path: defined?(notifications_settings_path) ? notifications_settings_path : nil
      },
      "payments" => {
        name: "Payment Info",
        path: defined?(payments_settings_path) ? payments_settings_path : nil
      }
    }
  end
end

app/views/settings/_side_bar.html.haml
.settings.container
  .row
    .col-md-3.col-sm-3
      %ul.nav.nav-pills.nav-stacked.settings-list
        - settings_list.each do |list|
          %li{class: active_list?(list[0], @current_settings) ? "active" : ""}
            = link_to list[1][:path] do
              %i.fa.fa-dot-circle-o
              = list[1][:name]
              - if active_list?(list[0], @current_settings)
                %i.fa.fa-arrow-right.pull-right
    .col-md-9.col-sm-9
      = validation_errors_notifications current_person
      = yield

app/views/settings/accounts.html.haml
= heading_section :h2, "Account Settings"
= render layout: "side_bar" do
  .panel.panel-default
    .panel-heading Account Settings
    .panel-body
      = form_for current_person, url: settings_path, method: :put, html: { multipart: true } do |f|
        .form-group
          = f.label :email
          = f.email_field :email, class: "form-control input-lg"
        .form-group
          = f.label :username
          = f.text_field :username, class: "form-control input-lg"
        .form-group
          = f.submit "Save Information", class: "btn btn-primary"
  .panel.panel-default
    .panel-heading
      %h3.panel-title Security Settings
    .panel-body
      = form_for current_person, url: settings_path, method: :put, html: { multipart: true } do |f|
        .form-group
          = f.label :password
          = f.password_field :password, class: "form-control input-lg"
        .form-group
          = f.label :password_confirmation
          = f.password_field :password_confirmation, class: "form-control input-lg"
        .form-group
          = f.submit "Update Password", class: "btn btn-primary"
  .panel.panel-danger
    .panel-heading
      %h3.panel-title Cancel your account
    .panel-body
      = button_to "Yes! Cancel", registration_path(current_person), class: "btn btn-default site-btn", data: { confirm: "Are you sure?" }, method: :delete

app/views/settings/notifications.html.haml
= heading_section :h2, "Notifications Settings"
= render layout: "side_bar" do
  = form_tag preferences_settings_path, method: :post do
    = fields_for :notification_preferences do |f|
      -# %h3 Newsletters
      -# .form-group
        = f.radio_button :newsletters, true, {checked: @preferences.include?(:newsletters)}
        = f.label :newsletters_true, "Send me a <strong>weekly</strong> newsletter if there are new listings".html_safe
        %br
        = f.radio_button :newsletters, false, {checked: !@preferences.include?(:newsletters)}
        = f.label :newsletters_false, "Don't send me newsletters"

      -# %h3 Emails from administrators
      -# .form-group
        = f.check_box :emails_from_administrator, {checked: @preferences.include?(:emails_from_administrator)}, true, false
        = f.label :emails_from_administrator, "I'm willing receive occasional emails from administrator"

      %h3 I want to get an email notification when ...
      .form-group
        = f.check_box :new_message, { checked: @preferences.include?(:new_message) }, true, false
        = f.label :new_message, "...someone sends me a message"
      -# .form-group
        = f.check_box :give_feedback, {checked: @preferences.include?(:give_feedback)}, true, false
        = f.label :send_message, "...someone gives me a feedback"
      -# .form-group
        = f.check_box :marks_order, {checked: @preferences.include?(:marks_order)}, true, false
        = f.label :marks_order, "...someone marks my order"
      .form-group
        = f.check_box :new_payment, { checked: @preferences.include?(:new_payment) }, true, false
        = f.label :new_payment, "...I receive a new payment"
      -# .form-group
        = f.check_box :following_new_post, {checked: @preferences.include?(:following_new_post)}, true, false
        = f.label :following_new_post, "...someone I follow posts new listing"

      .form-group
        = f.submit "Save Information", class: "btn btn-primary site-btn"

app/views/settings/payments.html.haml
= heading_section :h2, "Payments Settings"
= render layout: "side_bar" do
  = form_for current_person, url: settings_path, method: :put, html: { multipart: true } do |f|
    .form-group
      = f.label :paypal_id, "Your Paypal email address"
      = f.text_field :paypal_id, class: "form-control input-lg"
    .form-group
      = f.submit "Save Information", class: "btn btn-primary site-btn"

app/views/settings/profiles.html.haml
= heading_section :h2, "Settings"
- content_for :javascript do
  $location = new Location();
  $location.initializeLocation();
  $location.setMapForm();

  Profiles.validateForm();

= render layout: "side_bar" do
  %p This information is visible to all Threadhabits users in your profile page.
  = form_for current_person, url: settings_path, method: :put, html: { multipart: true, id: "editProfilesForm" } do |f|
    .form-group
      = f.label :first_name
      = f.text_field :first_name, class: "form-control input-lg"
    .form-group
      = f.label :last_name
      = f.text_field :last_name, class: "form-control input-lg"
    .form-group
      = f.fields_for :address do |n|
        = n.label :location
        = n.text_field :location, class: "form-control input-lg", id: "location_input"
        = n.hidden_field :latitude, class: "form-control input-lg", id: "latitude_input"
        = n.hidden_field :longitude, class: "form-control input-lg", id: "longitude_input"
        = n.hidden_field :place_id, class: "form-control input-lg", id: "place_id_input"
        #google-maps
    .form-group
      = f.label :about_you
      = f.text_area :about_you, class: "form-control input-lg", rows: 5

    .form-group
      = f.label :avatar, "Profile Image"
      = f.preview_image_field :avatar

    .form-group
      = f.label :avatar, "Cover Image"
      = f.preview_image_field :cover_image

    .form-group
      = f.label :phone_number
      = f.text_field :phone_number, class: "form-control input-lg"

    %blockquote.blockquote
      Social Media Links
    .form-group
      = f.label :facebook_profile
      = f.text_field :facebook_profile, class: "form-control input-lg"
    .form-group
      = f.label :instagram_profile
      = f.text_field :instagram_profile, class: "form-control input-lg"
    .form-group
      = f.label :twitter_profile
      = f.text_field :twitter_profile, class: "form-control input-lg"
    .form-actions
      = f.submit "Save Information", class: "btn btn-primary site-btn"